### ISSUE TITLE
Kit drops

### ISSUE THREAD

**Issue by Majestyc2k1** [BrainStone/SpacePackExtended#1]
#### What you expected to happen: Equal level Kit drops from Constructor (2-2, 3-3, 4-4, 5-5).

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11
- SpacePackExtended: 1.11-2.0.35-beta
- Forge: 13.19.1.2189
- Other related mods:

**Comment by BrainStone** [comment]
Fixed it. Will publish a release soon
